# Generated by Django 4.2.23 on 2025-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review'),
        ('accounts', '0003_alter_user_profilepic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='savedShops',
            field=models.ManyToManyField(related_name='savedByUsers', to='app.shop'),
        ),
        migrations.DeleteModel(
            name='SavedShops',
        ),
    ]
