services:

  backend:
    depends_on:
      - db
    build: ./backend
    volumes:
      - ./backend:/container-backend
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    depends_on:
      - backend
    build: ./frontend
    volumes:
      - ./frontend:/container-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: