# Generated by Django 4.2.23 on 2025-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
