# Generated by Django 4.2.23 on 2025-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='lat',
            field=models.FloatField(default=35.1709),
        ),
        migrations.AddField(
            model_name='shop',
            name='lng',
            field=models.FloatField(default=136.8815),
        ),
    ]
