# Generated by Django 4.2.23 on 2025-08-05 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_shop_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='コメントタイトル')),
                ('content', models.TextField(verbose_name='コメント本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='comments/', verbose_name='添付写真')),
                ('ratingStar', models.IntegerField(verbose_name='星')),
            ],
        ),
    ]
