# Generated by Django 4.2.23 on 2025-08-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment'),
        ('app', '0003_shop_lat_shop_lng'),
    ]

    operations = [
    ]
