# Generated by Django 4.2.23 on 2025-08-08 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_comment_shop_comment_user_alter_comment_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='shopimage',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='ShopImage',
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.ManyToManyField(related_name='shops', to='app.category'),
        ),
    ]
