# Generated by Django 4.2.23 on 2025-08-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_category_remove_shopimage_shop_remove_shop_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='categories',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='shop',
            name='categories',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
