# Generated by Django 4.2.23 on 2025-08-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='isSaved',
            field=models.BooleanField(default=False),
        ),
    ]
