# Generated by Django 4.2.23 on 2025-08-09 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_shop_issaved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='isSaved',
        ),
        migrations.CreateModel(
            name='ShopMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='app.shop')),
            ],
        ),
    ]
